sequenceDiagram
   
 participant Browser
    participant Server

    Note right of Browser: User types a note and clicks "Save"

    Browser->>Server: Sends the new note data (POST /new_note)
    activate Server
    Note right of Server: Server saves the note in storage
    Server-->>Browser: Responds with a redirect to /notes
    deactivate Server

    Browser->>Server: Requests the updated notes page (GET /notes)
    activate Server
    Server-->>Browser: Sends full HTML document of notes
    deactivate Server

    Note right of Browser: Browser reloads page and shows the updated note